### ISSUE TITLE
Incompatible node LATEST -  This version of uWS.js supports only Node.js LTS versions 16, 18 and 20 on (glibc) Li

### ISSUE THREAD

**Issue by VigilioYonatan** [nanoexpress/nanoexpress#702]
### Is you/your team sponsoring this project

- [ ] Yes
- [X ] No

### Minimal reproducible repo

Link here

### Current Behavior
```ts
import express from "nanoexpress";

const app = express();

app.listen(3000);
```

### Expected behavior/code

No compatibility  (Error: This version of uWS.js supports only Node.js LTS versions 16, 18 and 20 on (glibc) Linux, macOS and Windows, on Tier 1 [bun 1.19]
- OS: [Windows 10]
- Addinational Info: _type here_

**Comment by dalisoft** [comment]
Thank you for report @VigilioYonatan 

There are breaking changes on uWebSockets.js since latest nanoexpress release.
This project will be re-written partly but there other my projects in priority to make this project work

- release-me
- airlight

Currently release-me in semi-active development due of freelance job and open source coding. At open source coding release-me blocked by it's coverage system and it may take a while

**Comment by dalisoft** [comment]
@VigilioYonatan Thank you for report and today this fix will be shipped

**Comment by dalisoft** [comment]
This issue has been fixed on https://github.com/nanoexpress/nanoexpress/releases/tag/v6.4.4 release
