### ISSUE TITLE
Is handlebars supported in nanoexpress like expressjs?

### ISSUE THREAD

**Issue by victor-a-rigacci** [nanoexpress/nanoexpress#74]
Hi, im trying to run handlebars(view engine) with nanoexpress, any recommendation?

**Comment by dalisoft** [comment]
Hi @victor-a-rigacci 
Thanks for interesting to `nanoexpress`!

This project doesn't built to be used with `handlersbars` at beginning, because there none of user was mentioned this within `alpha` phase.

There has 3 options:
1. Create your own middleware (i don't how do you this, but anyway there has way)
2. See how looks like this manually adding
```ts
const contentOfTemplate: string = getSomehowYourHandlerbarFile();

app.get('/hi', (req: HttpRequest, res: HttpResponse): HttpResponse => res.end(contentOfTemplate({yourPropsHere})));
```
3. *This variant only if you don't have time to try out 2 options above*

Back to `express` or any of `Handlers` supported backend server framework (`Fastify`?)

**Comment by dalisoft** [comment]
@victor-a-rigacci Is your question was answered? If yes, please close issue. Thanks

**Comment by dalisoft** [comment]
No answer. I sure i already answered [here](https://github.com/nanoexpress/nanoexpress/issues/74#issuecomment-585914826)

**Comment by dalisoft** [comment]
@victor-a-rigacci As an option, you can become Sponsor with level *Pro patron* or higher and can ask feature you want
