### ISSUE TITLE
Method signature inconsistency - setNotFoundHandler

### ISSUE THREAD

**Issue by literakl** [nanoexpress/nanoexpress#84]
Every method in API has this sequence: req, res but notFound handler has an opposite

      errorHandlerCallback: (
        err: Error,
        req: HttpRequest,
        res: HttpResponse
      ) => HttpResponse

      validationErrorHandlerCallback: (
        errors: validationErrors,
        req: HttpRequest,
        res: HttpResponse
      ) => any

  type HttpRoute = (
    req: HttpRequest,
    res: HttpResponse,
    next?: Function,
    config?: object,
    previousMiddlewareResult?: any
  ) => any;

      notFoundHandlerCallback: (
        res: HttpResponseBasic,
        req: HttpRequestBasic
      ) => HttpRequestBasic

There is not much users yet, so you can break a backward compatibility and unify it.

**Comment by dalisoft** [comment]
Yes, currently `notFound` handler does not support `.header, .status, etc`, so this method definition is correct currently, users can `send` at high-performance as i remember something was caused this leave this method as is.
On PRO version (PRO is re-written simple version) the bug is fixed by using `Route` instance, in free version there no `Route` instance.

So, let's finalize:
1. Declaration was defined correctly
2. Not found handler works
3. Who needs modifications, uses `uWS Http(Request, Response)` instances to get what they need

**Comment by literakl** [comment]
You did not understand me. I was complaining about an parameter order. All methods have (req, res), but this particular method has opposite order (res, req). Good API is consistent.

**Comment by dalisoft** [comment]
Ah, now understand. I will fix it, but later, after some tests
