### ISSUE TITLE
How to use subscribe publish

### ISSUE THREAD

**Issue by ourfamilygithub** [nanoexpress/nanoexpress#88]
hello 
there is no guide to use subscribe / publish in docs
how can we do that?

**Comment by dalisoft** [comment]
Hi @ourfamilygithub 

Thanks for feature implementation request.

This library aims to support HTTP/WebSocket features. 
PubSub is not implemented, at least one method was exposed, but for test purposes. 
PubSub even for pro versions are not implemented as currently project focus is keep current project API and features, only bug-fixing because i have less time for adding new feature. 

Would you like create PR for adding this feature?

**Comment by dalisoft** [comment]
You can use subscribe / publish from uWebSockets.js.
There no PubSub feature was declared nor described and were no PR or answer within week, we can close this issue
