### ISSUE TITLE
websocket parameter wrong interface

### ISSUE THREAD

**Issue by yene** [nanoexpress/nanoexpress#89]
```
app.ws('/', (req, ws) => {
  ws.end(3, 'Close message');
});
```

Visual Studio Code reports that ws is from the interface HttpResponse.

**Comment by dalisoft** [comment]
Hi @yene 

Thanks for bug report. 
Can you create PR to fix this?

**Comment by bil-ash** [comment]
@dalisoft please check whether it is an error in only the docs or not because even the **uWS** parameters order is same as that of **ws** (ws,req) [.open = [](auto *ws, auto *req) ](https://github.com/uNetworking/uWebSockets/blob/master/misc/READMORE.md). I do not think that you have just changed the parameters order in the library without any reason.

**Comment by dalisoft** [comment]
I just changed order of function for compatibility.
I think a lot of peoples already know there should be `ws` not `httpResponse`, PR is welcome, but i cannot fix it currently or within current month

**Comment by dalisoft** [comment]
@bil-ash I fixed it, can you check please?
